language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
sudo: false
install:
    - pip install tox
script:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then tox -e coverage,coverage-report,flake8,doc8,pep257; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then tox -e coverage,coverage-report,flake8,doc8,pep257,mypy; fi
matrix:
    fast_finish: true
notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#django12factor"
        skip_join: true
        use_notice: true
